# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: volnux/protos/task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'volnux/protos/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18volnux/protos/task.proto\x12\x0e\x65vent_pipeline\"\xa0\x01\n\x11SubmitTaskRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\t\x12\x0f\n\x07timeout\x18\x05 \x01(\x03\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\x12\x11\n\tclient_id\x18\x07 \x01(\t\x12\x0c\n\x04hmac\x18\x08 \x01(\t\"\xb0\x01\n\x12SubmitTaskResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x0c\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x0c\n\x04\x63ode\x18\x06 \x01(\t\x12\x14\n\x0c\x63ompleted_at\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\x01\x12\x0c\n\x04hmac\x18\t \x01(\t\"H\n\x11QueryEventRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"l\n\x12QueryEventResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x11\n\tavailable\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x10\n\x08metadata\x18\x05 \x01(\t2\xfc\x02\n\x0cTaskExecutor\x12U\n\nSubmitTask\x12!.event_pipeline.SubmitTaskRequest\x1a\".event_pipeline.SubmitTaskResponse\"\x00\x12U\n\nQueryEvent\x12!.event_pipeline.QueryEventRequest\x1a\".event_pipeline.QueryEventResponse\"\x00\x12]\n\x10SubmitTaskStream\x12!.event_pipeline.SubmitTaskRequest\x1a\".event_pipeline.SubmitTaskResponse\"\x00\x30\x01\x12_\n\x10SubmitBatchTasks\x12!.event_pipeline.SubmitTaskRequest\x1a\".event_pipeline.SubmitTaskResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'volnux.protos.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITTASKREQUEST']._serialized_start=45
  _globals['_SUBMITTASKREQUEST']._serialized_end=205
  _globals['_SUBMITTASKRESPONSE']._serialized_start=208
  _globals['_SUBMITTASKRESPONSE']._serialized_end=384
  _globals['_QUERYEVENTREQUEST']._serialized_start=386
  _globals['_QUERYEVENTREQUEST']._serialized_end=458
  _globals['_QUERYEVENTRESPONSE']._serialized_start=460
  _globals['_QUERYEVENTRESPONSE']._serialized_end=568
  _globals['_TASKEXECUTOR']._serialized_start=571
  _globals['_TASKEXECUTOR']._serialized_end=951
# @@protoc_insertion_point(module_scope)
