name: Python Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi
    
    - name: Run tests with coverage
      run: pytest --cov=. --cov-report=xml
      # '--cov=.' tells pytest-cov to check coverage for all files in the current directory
      # '--cov-report=xml' generates the xml report required by Codecov
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
