name: Profile Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and snakeviz
        run: |
          # Install your library's dependencies. 
          # Adjust the command based on your project setup (e.g., install -e . or pip install -r requirements.txt).
          pip install -e . 
          pip install snakeviz

      - name: Run linear pipeline and capture .prof file
        # The -o flag is used with cProfile to write the profile data to a file.
        run: python3 profiling/profiler.py -t linear -o profile_results_linear.prof

      - name: Generate text report for linear pipeline
        run: |
          if [ -f profile_results_linear.prof ]; then
            python3 -c "import pstats; p = pstats.Stats('profile_results_linear.prof'); p.sort_stats('cumtime').print_stats()" > profile_report_linear.txt
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_linear.prof

      - name: Upload profile artifact for linear pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-linear-pr
          path: profile_report_linear.txt

      - name: Upload .prof artifact for linear pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-data-linear
          path: profile_results_linear.prof

      - name: Run linear pipeline with result piping and capture .prof file for PR
        run: python3 profiling/profiler.py -t linear_pr -o profile_results_linear_pr.prof

      - name: Generate text report for linear pipeline with result piping
        run: |
          if [ -f profile_results_linear_pr.prof ]; then
              python3 -c "import pstats; p = pstats.Stats('profile_results_linear_pr.prof'); p.sort_stats('cumtime').print_stats()" > profile_report_linear_pr.txt
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_linear_pr.prof

      - name: Upload profile artifact for linear pipeline with result piping
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-linear-pr
          path: profile_report_linear_pr.txt
      
      - name: Upload .prof artifact for linear pipeline with result piping
        uses: actions/upload-artifact@v4
        with:
          name: profile-data-linear-pr
          path: profile_results_linear_pr.prof

      - name: Run parallel pipeline and capture .prof file
        run: python3 profiling/profiler.py -t parallel -o profile_results_parallel.prof

      - name: Generate snakeviz report for parallel pipeline
        run: |
          if [ -f profile_results_parallel.prof ]; then
              python3 -c "import pstats; p = pstats.Stats('profile_results_parallel.prof'); p.sort_stats('cumtime').print_stats()" > profile_report_parallel.txt
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_parallel.prof

      - name: Upload profile artifact for parallel pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-parallel
          path: profile_report_parallel.txt

      - name: Upload .prof artifact for parallel pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-data-parallel
          path: profile_results_parallel.prof


      - name: Run decision tree pipeline and capture .prof file
        run: python3 profiling/profiler.py -t decision_tree -o profile_results_decision_tree.prof

      - name: Generate text report for decision tree pipeline
        run: |
          if [ -f profile_results_decision_tree.prof ]; then
              python3 -c "import pstats; p = pstats.Stats('profile_results_decision_tree.prof'); p.sort_stats('cumtime').print_stats()" > profile_report_decision_tree.txt
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_decision_tree.prof
      
      - name: Upload profile artifact for decision tree pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-decision-tree
          path: profile_report_decision_tree.txt

      - name: Upload .prof artifact for decision tree pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-data-decision-tree
          path: profile_results_decision_tree.prof

      - name: Run batch pipeline and capture .prof file
        run: python3 profiling/profiler.py -t batch -o profile_results_batch.prof

      - name: Generate snakeviz report for batch pipeline
        run: |
          if [ -f profile_results_batch.prof ]; then
              python3 -c "import pstats; p = pstats.Stats('profile_results_batch.prof'); p.sort_stats('cumtime').print_stats()" > profile_report_batch.txt
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_batch.prof

      - name: Upload profile artifact for batch pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-batch
          path: profile_report_batch.txt

      - name: Upload .prof artifact for batch pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-data-batch
          path: profile_results_batch.prof
