name: Profile Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and snakeviz
        run: |
          # Install your library's dependencies. 
          # Adjust the command based on your project setup (e.g., install -e . or pip install -r requirements.txt).
          pip install -e . 
          pip install snakeviz

      - name: Run linear pipeline and capture .prof file
        # The -o flag is used with cProfile to write the profile data to a file.
        run: python3 profiling/profiler.py -t linear -o profile_results_linear.prof

      - name: Generate snakeviz report for linear pipeline
        # snakeviz is run with --browser to force it to output to stdout, then redirected to a file.
        run: |
          if [ -f profile_results_linear.prof ]; then
            snakeviz --browser profile_results_linear.prof > profile_report_linear.html
          else
            echo "Profile file not found. Skipping snakeviz."
            ls -la
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_linear.prof

      - name: Upload profile artifact for linear pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-linear-pr
          path: profile_report_linear.html

      - name: Run linear pipeline with result piping and capture .prof file for PR
        run: python3 profiling/profiler.py -t linear_pr -o profile_results_linear_pr.prof

      - name: Generate snakeviz report for linear pipeline with result piping
        run: |
          if [ -f profile_results_linear_pr.prof ]; then
            snakeviz --browser profile_results_linear_pr.prof > profile_report_linear_pr.html
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_linear_pr.prof

      - name: Upload profile artifact for linear pipeline with result piping
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-linear-pr
          path: profile_report_linear_pr.html

      - name: Run parallel pipeline and capture .prof file
        run: python3 profiling/profiler.py -t parallel -o profile_results_parallel.prof

      - name: Generate snakeviz report for parallel pipeline
        run: |
          if [ -f profile_results_parallel.prof ]; then
            snakeviz --browser profile_results_parallel.prof > profile_report_parallel.html
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_parallel.prof

      - name: Upload profile artifact for parallel pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-parallel
          path: profile_report_parallel.html

      - name: Run batch pipeline and capture .prof file
        run: python3 profiling/profiler.py -t batch -o profile_results_batch.prof

      - name: Generate snakeviz report for batch pipeline
        run: |
          if [ -f profile_results_batch.prof ]; then
            snakeviz --browser profile_results_batch.prof > profile_report_batch.html
          else
            echo "Profile file not found. Skipping snakeviz."
            exit 1
          fi
        env:
          PROFILER_OUTPUT_FILE: profile_results_batch.prof

      - name: Upload profile artifact for batch pipeline
        uses: actions/upload-artifact@v4
        with:
          name: profile-report-batch
          path: profile_report_batch.html
